-- MySQL Script generated by MySQL Workbench
-- qui 21 nov 2019 22:34:47 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE SCHEMA IF NOT EXISTS `simulado_online` ;
USE `simulado_online` ;

-- -----------------------------------------------------
-- Table `simulado_online`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simulado_online`.`aluno` (
  `id` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(40) NOT NULL,
  `pontuacao` INT(5) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


-- -----------------------------------------------------
-- Table `simulado_online`.`professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simulado_online`.`professor` (
  `id` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(80) NOT NULL,
  `senha` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC));


-- -----------------------------------------------------
-- Table `simulado_online`.`questao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `simulado_online`.`questao` (
  `id` INT(6) UNSIGNED NOT NULL AUTO_INCREMENT,
  `enunciado` TEXT(1000) NOT NULL,
  `alternativa_a` TEXT(350) NULL,
  `alternativa_b` TEXT(350) NULL,
  `alternativa_c` TEXT(350) NULL,
  `alternativa_d` TEXT(350) NULL,
  `alternativa_e` TEXT(350) NULL,
  `correta` ENUM('a', 'b', 'c', 'd', 'e') NULL,
  `materia` VARCHAR(45) NOT NULL,
  `professor_id` INT(6) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questao_professor_idx` (`professor_id` ASC),
  CONSTRAINT `fk_questao_professor`
    FOREIGN KEY (`professor_id`)
    REFERENCES `simulado_online`.`professor` (`id`));
